"""
agent_reporter.py — Reads applications_log.json, generates output/final_report.md.
Uses claude -p via claude_cli.py — no API key needed.
"""

from __future__ import annotations

import json
import logging
from collections import Counter
from datetime import datetime
from pathlib import Path

import yaml

from claude_cli import call_claude

logging.basicConfig(level=logging.INFO, format="%(asctime)s [reporter] %(message)s")
log = logging.getLogger(__name__)

INPUT_FILE = Path("output/applications_log.json")
FILTERED_FILE = Path("output/jobs_filtered.json")
REPORT_FILE = Path("output/final_report.md")
CONFIG_FILE = Path("config.yaml")


def load_config() -> dict:
    with open(CONFIG_FILE) as f:
        return yaml.safe_load(f)


# ---------------------------------------------------------------------------
# JD summarizer
# ---------------------------------------------------------------------------

def summarize_jd(job: dict) -> str:
    jd = job.get("full_description") or job.get("description_snippet", "")
    if not jd:
        return f"{job.get('title', 'Unknown')} at {job.get('company', 'Unknown')}."

    prompt = f"""Summarize this job description in 2-3 concise sentences. Focus on:
- What the company does
- Key responsibilities
- Required tech stack / skills

Job: {job.get('title')} at {job.get('company')}
Description:
{jd[:2000]}

Return only the summary text, no headers or bullet points."""

    result = call_claude(prompt)
    return result.strip() if result else jd[:300] + "..."


# ---------------------------------------------------------------------------
# Resume diff
# ---------------------------------------------------------------------------

def generate_resume_diff(job: dict) -> str:
    keywords = job.get("keywords", [])
    reasoning = job.get("relevance_reasoning", "")
    seniority = job.get("seniority", "mid")

    prompt = f"""A resume was tailored for this job:
- Role: {job.get('title')} at {job.get('company')}
- Key keywords: {', '.join(keywords) if keywords else 'N/A'}
- Relevance score: {job.get('relevance_score', 'N/A')}/10
- Seniority: {seniority}
- Why selected: {reasoning}

Write exactly 2 bullet points describing the resume tailoring changes:
- What was emphasized or reordered
- What keywords were added

Return only the 2 bullet points, no preamble."""

    result = call_claude(prompt)
    if result:
        return result.strip()
    return f"- Keywords added: {', '.join(keywords)}\n- Resume reordered for {seniority}-level fit"


# ---------------------------------------------------------------------------
# Report builder
# ---------------------------------------------------------------------------

def build_report(
    app_log: list[dict],
    filtered_jobs: list[dict],
    config: dict,
) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    job_details: dict[str, dict] = {j["id"]: j for j in filtered_jobs}

    total = len(app_log)
    by_status = Counter(e.get("status", "unknown") for e in app_log)
    by_platform = Counter(e.get("platform", "unknown") for e in app_log)
    by_company = Counter(e.get("company", "unknown") for e in app_log)

    applied_ids = {e["job_id"] for e in app_log}
    locations = [
        job_details[jid]["location"]
        for jid in applied_ids
        if jid in job_details
    ]
    by_location = Counter(loc.split(",")[0].strip() for loc in locations)

    lines: list[str] = []

    lines.append(f"# Job Hunt Report — {now}\n")
    lines.append("> Generated by multi-agent job hunting system\n")
    lines.append("")

    lines.append("## Summary\n")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total Applications | {total} |")
    lines.append(f"| Successfully Applied | {by_status.get('applied', 0)} |")
    lines.append(f"| Dry Run / Pending | {by_status.get('dry_run', 0)} |")
    lines.append(f"| Skipped (manual) | {by_status.get('skipped', 0) + by_status.get('manual_review', 0)} |")
    lines.append(f"| Errors | {by_status.get('error', 0)} |")
    lines.append("")

    lines.append("## Applications by Platform\n")
    lines.append("| Platform | Count |")
    lines.append("|----------|-------|")
    for platform, count in by_platform.most_common():
        lines.append(f"| {platform.title()} | {count} |")
    lines.append("")

    lines.append("## Applications by Location\n")
    lines.append("| Location | Count |")
    lines.append("|----------|-------|")
    for loc, count in by_location.most_common(10):
        lines.append(f"| {loc} | {count} |")
    lines.append("")

    lines.append("## Detailed Applications\n")

    successful = [e for e in app_log if e.get("status") == "applied"]
    pending = [e for e in app_log if e.get("status") not in ("applied", "error")]
    errors = [e for e in app_log if e.get("status") == "error"]

    def render_entry(entry: dict, idx: int, with_llm: bool = True) -> list[str]:
        jid = entry["job_id"]
        job = job_details.get(jid, {})
        out = []
        score = job.get("relevance_score", "N/A")
        out.append(f"### {idx}. {entry['job_title']} @ {entry['company']}")
        out.append(f"- **Status**: `{entry.get('status', 'unknown').upper()}`")
        out.append(f"- **Platform**: {entry.get('platform', 'unknown')}")
        out.append(f"- **URL**: {entry.get('job_url', 'N/A')}")
        out.append(f"- **Applied At**: {entry.get('applied_at', 'N/A')}")
        out.append(f"- **Resume**: `{Path(entry.get('resume_path', 'N/A')).name}`")
        out.append(f"- **Relevance Score**: {score}/10")
        if job.get("location"):
            out.append(f"- **Location**: {job['location']}")
        if entry.get("reason"):
            out.append(f"- **Note**: {entry['reason']}")
        out.append("")

        if with_llm and job:
            log.info("  Summarizing JD for %s...", entry["company"])
            summary = summarize_jd(job)
            out.append("**JD Summary:**")
            out.append(f"> {summary}")
            out.append("")
            diff = generate_resume_diff(job)
            out.append("**Resume Tailoring:**")
            out.append(diff)
            out.append("")

        return out

    if successful:
        lines.append("### ✅ Successfully Applied\n")
        for i, entry in enumerate(successful, 1):
            lines.extend(render_entry(entry, i))

    if pending:
        lines.append("### ⏳ Pending / Manual Review\n")
        for i, entry in enumerate(pending, 1):
            lines.extend(render_entry(entry, i, with_llm=False))

    if errors:
        lines.append("### ❌ Errors\n")
        for entry in errors:
            lines.append(f"- **{entry['company']}**: {entry.get('reason', 'Unknown error')}")
        lines.append("")

    lines.append("## Top Companies Applied To\n")
    for company, count in by_company.most_common(10):
        lines.append(f"- {company} ({count} position{'s' if count > 1 else ''})")
    lines.append("")

    lines.append("## Configuration Used\n")
    lines.append(f"- **Job Titles**: {', '.join(config.get('job_titles', []))}")
    lines.append(f"- **Target States**: {', '.join(config.get('target_states', []))}")
    lines.append(f"- **Work Type**: {config.get('work_type', 'any')}")
    lines.append(f"- **Min Relevance Score**: {config.get('min_relevance_score', 6)}/10")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run(app_log: list[dict] | None = None) -> str:
    config = load_config()

    if app_log is None:
        if not INPUT_FILE.exists():
            log.error("Input file not found: %s — run agent_applier first", INPUT_FILE)
            return ""
        app_log = json.loads(INPUT_FILE.read_text())

    filtered_jobs: list[dict] = []
    if FILTERED_FILE.exists():
        filtered_jobs = json.loads(FILTERED_FILE.read_text())

    log.info("Generating report for %d applications...", len(app_log))
    report = build_report(app_log, filtered_jobs, config)

    REPORT_FILE.parent.mkdir(parents=True, exist_ok=True)
    REPORT_FILE.write_text(report)
    log.info("Report saved to %s", REPORT_FILE)
    return report


if __name__ == "__main__":
    run()
